FROM golang:bookworm

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
# We use the generic test command for e2e
ENV CGO_ENABLED=0
CMD ["go", "test", "-v", "-count=1", "./tests/e2e/..."]
