[tasks.build]
description = "Build the Tandoor MCP binary into the dist directory"
run = "mkdir -p dist && go build -o dist/tandoor-mcp ./src/"

[tasks.test-e2e-docker]
description = "Run the E2E tests using Docker Compose"
run = """
trap 'docker-compose down' EXIT
docker-compose up --build --remove-orphans tandoor-db tandoor-web tandoor-setup mcp-api -d
docker-compose run --rm --build e2e-tests
"""

[tools]
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
